### ISSUE TITLE
Cannot find module ngx-indexed-db

### ISSUE THREAD

**Issue by emmansayson** [assuncaocharles/ngx-indexed-db#48]
Hi, i'm importing it in my angular 7 service class, but building it always throws "webpackMissingModule() { var e = new Error("**Cannot find module \"ngx-indexed-db\**""); e.code = 'MODULE_NOT_FOUND'; throw e; }"

**Comment by emmansayson** [comment]
It's working fine in version 2.0.5. Maybe something has broken in the latest versions. Thanks.

**Comment by zac-farrugia** [comment]
Also experiencing the same reported issue, with this error:
```
ERROR in src/app/features/photos/models/photo-storage.model.ts(6,28): error TS2307: Cannot find module 'ngx-indexed-db'.  
src/app/features/photos/photo.service.ts(8,28): error TS2307: Cannot find module 'ngx-indexed-db'.
```

**Comment by maxegghead** [comment]
yep same problem for me.  Almost looks like npm is downloading src not dist version perhaps?

**Comment by assuncaocharles** [comment]
Fixed on version @2.0.8. Sorry for the problems caused
