### ISSUE TITLE
My collections in database are not being created

### ISSUE THREAD

**Issue by GabrielSilla** [assuncaocharles/ngx-indexed-db#255]
Hey There! Have an issue here hehe

For some reason my collections are not being created. However, i can find the database in my browser. But Angular is always throwing exceptions like "**core.js:6210 ERROR objectStore does not exists: membros**" for all my collections.

I followed the usage tutorial avaliable in NPM, however, no success yet =[

This is my DbConfig.
![Capturar](https://user-images.githubusercontent.com/16212063/120535483-66714f00-c3b9-11eb-8e05-cc6b75511061.PNG)

I am using it like the tutorial example, with "**NgxIndexedDBModule.forRoot(dbConfig)**" in the imports section

**Comment by evilstiefel** [comment]
Same issue here. Works fine with 6.1.2 in my other project, but the current version published (9.x) doesn't create the object stores anymore on a fresh site with no DB present.

**Comment by jensdwul1** [comment]
Also running into this issue. More specifically using a Angular 12 setup and the latest release.
I tried running both the 8.1 & the 6.1.2 versions additionally without success.

**Comment by evilstiefel** [comment]
You can run 6.1.2, but you have to make sure you delete the application data (or at least the idb) first, since 6.1.2 will not try to recreate the DB if it was already created by a later version (but still missing the object store).

**Comment by assuncaocharles** [comment]
Can you reproduce it in a codesandbox ?

**Comment by jensdwul1** [comment]
Hi there,
Not sure if this example is suitable as it's pretty straight forward but definitely running into issues
https://codesandbox.io/s/wonderful-dhawan-xr542?file=/src/app/app.module.ts

**Comment by limecakeio** [comment]
We've had to mitigate this issue by later calling createObjectStore(storeSchema) explicitly in order to initialize our object stores within the already existing DB. Surely, we'd expect this to take place as part of the DB initialization process as it did in the previous versions.
